version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: sentiment_analysis_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentiment_analysis
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  init_tweets:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  db_data:
